name: devlokos_podcast
description: "DevLokos App - Lista de episodios con scraping de YouTube"
publish_to: 'none'

version: 1.0.2+102

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.6
  go_router: ^12.1.3
  
  # State Management - BLoC
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # YouTube & Media
  youtube_player_flutter: ^9.1.3
  pod_player: ^0.2.2
  cached_network_image: ^3.3.1
  
  # HTTP & Scraping
  http: ^1.1.2
  html: ^0.15.4
  
  # Firebase - using latest versions to fix PigeonUserDetails error
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_remote_config: ^5.0.5
  firebase_storage: ^12.3.2
  
  # Utils
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.5
  share_plus: ^7.2.2
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  flutter_lints: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  
  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

# Configuración de íconos de la aplicación DevLokos
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#000000" # Negro de marca
    theme_color: "#FF914D" # Naranja de marca
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 256 # Tamaño más grande para mejor calidad
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"