// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSVo_XuC7P_oLbwbAa6V4zyaQ93MrhsO4',
    appId: '1:458512617441:web:c38d499d355577519c8ca0',
    messagingSenderId: '458512617441',
    projectId: 'devlokos',
    authDomain: 'devlokos.firebaseapp.com',
    storageBucket: 'devlokos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSVo_XuC7P_oLbwbAa6V4zyaQ93MrhsO4',
    appId: '1:458512617441:android:c38d499d355577519c8ca0',
    messagingSenderId: '458512617441',
    projectId: 'devlokos',
    storageBucket: 'devlokos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGc1OxjpFeHG2gkgBrKo23tLuNS3bYaKc',
    appId: '1:458512617441:ios:0ba9e4d01804938b9c8ca0',
    messagingSenderId: '458512617441',
    projectId: 'devlokos',
    storageBucket: 'devlokos.firebasestorage.app',
    iosBundleId: 'com.devlokos.devlokosdart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-messaging-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.devlokos.devlokosdart',
  );
}